version: '3'

services:
    orders:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/case-study-2-food-delivery-example-d:orders
        build: 
            context: './services/orders/'
            dockerfile: './Dockerfile'
        ports:
            - "5000:5000"
    delivery_auth:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/case-study-2-food-delivery-example-d:auth
        build: 
            context: './services/auth/'
            dockerfile: './Dockerfile'
        ports:
            - "5001:5001"



